# slot meta
slot_meta = ['景点-领域', '景点-名称', '景点-地址', '景点-地铁', '景点-电话', '景点-门票', '景点-游玩时间', '景点-评分', '餐馆-名称', '餐馆-地址', '餐馆-地铁', '餐馆-电话', '餐馆-营业时间', '餐馆-推荐菜', '餐馆-人均消费', '餐馆-评分', 
'酒店-名称', '酒店-酒店类型', '酒店-地址', '酒店-地铁', '酒店-电话', '酒店-价格', '酒店-评分', 
'地铁-名称', '地铁-地铁', '出租-车型', '出租-车牌']

# state meta
state_meta = ['景点-名称', '景点-门票','景点-游玩时间','景点-评分','景点-周边景点','景点-周边餐馆','景点-周边酒店',
'餐馆-名称', '餐馆-推荐菜', '餐馆-人均消费', '餐馆-评分', '餐馆-周边景点', '餐馆-周边餐馆', '餐馆-周边酒店',
'酒店-名称', '酒店-酒店类型', '酒店-价格', '酒店-酒店设施', '酒店-评分', '酒店-周边景点', '酒店-周边餐馆', '酒店-周边酒店',
'地铁-出发地', '地铁-目的地', '出租-出发地', '出租-目的地']

# user da
usr_da_voc = ["General+bye+none+none",
"General+greet+none+none",
"General+thank+none+none",
"Inform+出租+出发地+1",
"Inform+出租+目的地+1",
"Inform+出租+目的地+2",
"Inform+地铁+出发地+1",
"Inform+地铁+目的地+1",
"Inform+地铁+目的地+2",
"Inform+景点+名称+1",
"Inform+景点+名称+2",
"Inform+景点+名称+3",
"Inform+景点+名称+4",
"Inform+景点+游玩时间+1",
"Inform+景点+评分+1",
"Inform+景点+门票+1",
"Inform+酒店+价格+1",
"Inform+酒店+名称+1",
"Inform+酒店+名称+2",
"Inform+酒店+名称+3",
"Inform+酒店+评分+1",
"Inform+酒店+酒店类型+1",
"Inform+酒店+酒店设施-24小时热水+1",
"Inform+酒店+酒店设施-SPA+1",
"Inform+酒店+酒店设施-中式餐厅+1",
"Inform+酒店+酒店设施-会议室+1",
"Inform+酒店+酒店设施-健身房+1",
"Inform+酒店+酒店设施-免费国内长途电话+1",
"Inform+酒店+酒店设施-免费市内电话+1",
"Inform+酒店+酒店设施-公共区域和部分房间提供wifi+1",
"Inform+酒店+酒店设施-公共区域提供wifi+1",
"Inform+酒店+酒店设施-叫醒服务+1",
"Inform+酒店+酒店设施-吹风机+1",
"Inform+酒店+酒店设施-商务中心+1",
"Inform+酒店+酒店设施-国际长途电话+1",
"Inform+酒店+酒店设施-室内游泳池+1",
"Inform+酒店+酒店设施-室外游泳池+1",
"Inform+酒店+酒店设施-宽带上网+1",
"Inform+酒店+酒店设施-所有房间提供wifi+1",
"Inform+酒店+酒店设施-接待外宾+1",
"Inform+酒店+酒店设施-接机服务+1",
"Inform+酒店+酒店设施-接站服务+1",
"Inform+酒店+酒店设施-收费停车位+1",
"Inform+酒店+酒店设施-无烟房+1",
"Inform+酒店+酒店设施-早餐服务+1",
"Inform+酒店+酒店设施-早餐服务免费+1",
"Inform+酒店+酒店设施-暖气+1",
"Inform+酒店+酒店设施-桑拿+1",
"Inform+酒店+酒店设施-棋牌室+1",
"Inform+酒店+酒店设施-残疾人设施+1",
"Inform+酒店+酒店设施-洗衣服务+1",
"Inform+酒店+酒店设施-温泉+1",
"Inform+酒店+酒店设施-看护小孩服务+1",
"Inform+酒店+酒店设施-租车+1",
"Inform+酒店+酒店设施-行李寄存+1",
"Inform+酒店+酒店设施-西式餐厅+1",
"Inform+酒店+酒店设施-部分房间提供wifi+1",
"Inform+酒店+酒店设施-酒吧+1",
"Inform+酒店+酒店设施-酒店各处提供wifi+1",
"Inform+餐馆+人均消费+1",
"Inform+餐馆+名称+1",
"Inform+餐馆+名称+2",
"Inform+餐馆+推荐菜+1",
"Inform+餐馆+推荐菜+2",
"Inform+餐馆+推荐菜+3",
"Inform+餐馆+评分+1",
"Request+出租+车型+",
"Request+出租+车牌+",
"Request+地铁+出发地附近地铁站+",
"Request+地铁+目的地附近地铁站+",
"Request+景点+名称+",
"Request+景点+周边景点+",
"Request+景点+周边酒店+",
"Request+景点+周边餐馆+",
"Request+景点+地址+",
"Request+景点+游玩时间+",
"Request+景点+电话+",
"Request+景点+评分+",
"Request+景点+门票+",
"Request+酒店+价格+",
"Request+酒店+名称+",
"Request+酒店+周边景点+",
"Request+酒店+周边餐馆+",
"Request+酒店+地址+",
"Request+酒店+电话+",
"Request+酒店+评分+",
"Request+酒店+酒店类型+",
"Request+酒店+酒店设施-24小时热水+",
"Request+酒店+酒店设施-SPA+",
"Request+酒店+酒店设施-中式餐厅+",
"Request+酒店+酒店设施-会议室+",
"Request+酒店+酒店设施-健身房+",
"Request+酒店+酒店设施-免费国内长途电话+",
"Request+酒店+酒店设施-免费市内电话+",
"Request+酒店+酒店设施-公共区域和部分房间提供wifi+",
"Request+酒店+酒店设施-公共区域提供wifi+",
"Request+酒店+酒店设施-叫醒服务+",
"Request+酒店+酒店设施-吹风机+",
"Request+酒店+酒店设施-商务中心+",
"Request+酒店+酒店设施-国际长途电话+",
"Request+酒店+酒店设施-室内游泳池+",
"Request+酒店+酒店设施-室外游泳池+",
"Request+酒店+酒店设施-宽带上网+",
"Request+酒店+酒店设施-所有房间提供wifi+",
"Request+酒店+酒店设施-接待外宾+",
"Request+酒店+酒店设施-接机服务+",
"Request+酒店+酒店设施-接站服务+",
"Request+酒店+酒店设施-收费停车位+",
"Request+酒店+酒店设施-无烟房+",
"Request+酒店+酒店设施-早餐服务+",
"Request+酒店+酒店设施-早餐服务免费+",
"Request+酒店+酒店设施-暖气+",
"Request+酒店+酒店设施-桑拿+",
"Request+酒店+酒店设施-棋牌室+",
"Request+酒店+酒店设施-残疾人设施+",
"Request+酒店+酒店设施-洗衣服务+",
"Request+酒店+酒店设施-温泉+",
"Request+酒店+酒店设施-看护小孩服务+",
"Request+酒店+酒店设施-租车+",
"Request+酒店+酒店设施-行李寄存+",
"Request+酒店+酒店设施-西式餐厅+",
"Request+酒店+酒店设施-部分房间提供wifi+",
"Request+酒店+酒店设施-酒吧+",
"Request+酒店+酒店设施-酒店各处提供wifi+",
"Request+餐馆+人均消费+",
"Request+餐馆+名称+",
"Request+餐馆+周边景点+",
"Request+餐馆+周边酒店+",
"Request+餐馆+周边餐馆+",
"Request+餐馆+地址+",
"Request+餐馆+推荐菜+",
"Request+餐馆+电话+",
"Request+餐馆+营业时间+",
"Request+餐馆+评分+",
"Select+景点+源领域+景点",
"Select+景点+源领域+酒店",
"Select+景点+源领域+餐馆",
"Select+酒店+源领域+景点",
"Select+酒店+源领域+餐馆",
"Select+餐馆+源领域+景点",
"Select+餐馆+源领域+酒店",
"Select+餐馆+源领域+餐馆"]

def getSlotMeta():
  usr_da_slot = []
  for da in usr_da_voc:
    da_list = da.split('+')
    if da_list[0] != 'General':
      if '酒店设施' not in da_list[2]:
        usr_da_slot.append(da_list[1] + '-' + da_list[2].replace('-', '~'))
        # usr_da_slot.append(da_list[1] + '-' + da_list[2].replace('-', '~'))
  return state_meta